### ISSUE TITLE
tech stack icons are either missing or are misaligned

### ISSUE THREAD

**Issue by AdelBeit** [tsAppDevelopment/portfolio-v2-nextjs#6]
is this supposed to look like this?

![image](https://user-images.githubusercontent.com/8835499/207533546-2d34a587-b2ba-408a-9658-139cb2c86c77.png)

**Comment by teaguestockwell** [comment]
You're right. It looks like the last icon is missing. Thanks for pointing this out. It looks like a bad array split [here](https://github.com/teaguestockwell/portfolio-v2-nextjs/blob/ee88c084406155134b6d94c82d6be5d9bcc5d866/src/components/svgs.tsx#L293).
